### ISSUE TITLE
Question about Day 07

### ISSUE THREAD

**Issue by Ewa-Anna** [mebeim/aoc#23]
Hello,

I was wondering if you could please kindly look at [my code](https://github.com/Ewa-Anna/Advent-of-Code-2023/blob/main/Day_07/advent_of_code_day_7_part_1.py), an attmept to solve AoC puzzle on Day 07 and maybe give me a little hint what am I doing incorrectly? I am not sure where I am making a mistake and I feel like I am close to solution and yet no there.
I would be very grateful for your help and I hope I am not violating rules on your repository with this question. Apologies if I do.

Thank you,
Ewa

**Comment by aymanhs** [comment]
Not speaking for the owner of this repo or anyone else who may want to
help.  But the best way to get assistance is through the aoc reddit

**Comment by mebeim** [comment]
@Ewa-Anna hello, you aren't violating any rules don't worry about it 😄, but @aymanhs is right that this isn't really the right place to ask (also, Issues should be used for... well, *issues* you find in the repo, a discussion would be more appropriate for this question). You should ask on [the subreddit](https://www.reddit.com/r/adventofcode) instead (please read the rules there first and use [an appropriate post title](https://www.reddit.com/r/adventofcode/wiki/posts/standardized_titles/)!). 

In any case, I can see from a quick glance at the code that:

- The `score()` function seems OK to me, so the problem is somewhere else.
- You are sorting the cards in the hands with your `custom_sort()`. That's not something that you should do, read the rules more carefully.
