### ISSUE TITLE
optimize iterations in day24 part 2

### ISSUE THREAD

**Issue by edelans** [mebeim/aoc#5]
hello @mebeim :wave: , 

In today's puzzle part2, I noticed that for the rule 

```
Any white tile with exactly 2 black tiles immediately adjacent to it is flipped to black.
```

 you iterate over much more tiles than you could : 

https://github.com/mebeim/aoc/blob/c6776ff89d95c067d5a07b89f56292158125eac9/2020/solutions/day24.py#L31

you could restrict your iteration over the neighbors of the neighbors of your black tiles, cf my implem here : 

https://github.com/edelans/aoc2020/blob/933ae61307ad48b38b3aacdbc1e211d4f33b1937/day24.py#L73,L79

thanks again for your clean walkthrough, and buon Natale !

**Comment by mebeim** [comment]
You make a great point, indeed I do not need to check *all* those tiles since most of them will probably be surrounded by white tiles. That's something I was initially thinking about, but I didn't come up with a clean implementation right away and I forgot about it. I guess this also applies to day 17. Thank you very much! I'll optimize that for sure soon. 

Buon Natale anche a te! :christmas_tree:

**Comment by mebeim** [comment]
Done @edelans! This is quite faster and also a lot smoother. Thanks again! :smile: 

https://github.com/mebeim/aoc/blob/d4f09f9815665690c475b7302ac3010c05929e8d/2020/solutions/day24.py#L29-L42

**Comment by edelans** [comment]
@mebeim sweet ! 

To be honest at first I thought your new version was overlooking tiles already in the grid by only iterating over the neighbors. So I wondered if there would be a case where this could go wrong : 

1. a tile could be in the grid at the start of an iteration
2. but not in the neighbors you iterate over 
3. and which should stay in the grid at the end of an iteration

1 + 2 is equivalent to having a black tile with zero neighbor, the rules states they should be flipped to white, so fortunately, it's incompatible with 3. So in the end, it's ok to iterate only over neighbors. 


But then you might want to change the following formulation in your walkthrough : 

> For this reason, when evolving the grid, we need to also check all tiles surrounding the ones we already have, even if they are not in our grid set.

as after reading this (especially the "also"), you expect to see code iterating over `grid + neighbors`.

you could update it for something like : 

> For this reason, when evolving the grid, we need to check grid tiles and all their surrounding tiles, even if they are not in our grid set. And actually, all the grid tiles will be included in the surrounding tiles except the tiles that have 0 surrounding black tile. Those black tiles are flipped to white, so in the end we can restrict our iteration on the surrounding tiles alone.

**Comment by mebeim** [comment]
@edelans nice catch. Indeed, not including the tile itself was an oversight, but as you explained it ends up working anyway because of the evolution rules. I have updated the relevant parts of the walkthrough in 7a60dd4aedf255e125de8191891517af1da0e76d to reflect this, opting for a little bit longer (but hopefully clearer) explanation.
